// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdPbPGdZweNvKS6kYFweBY_ZLrBrcGrHg',
    appId: '1:523510024166:web:2898854c200bd14dee3827',
    messagingSenderId: '523510024166',
    projectId: 'v3ridia',
    authDomain: 'v3ridia.firebaseapp.com',
    storageBucket: 'v3ridia.firebasestorage.app',
    measurementId: 'G-NSZ5K3N9KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR2NfYixALChrndoak_GiqWrxljcqNQ1c',
    appId: '1:523510024166:android:671b0ef6b275a3fdee3827',
    messagingSenderId: '523510024166',
    projectId: 'v3ridia',
    storageBucket: 'v3ridia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa5sXgBdWY3FUn4JNNwcIuO1lYVKbkblI',
    appId: '1:523510024166:ios:8d7cf49afc46f497ee3827',
    messagingSenderId: '523510024166',
    projectId: 'v3ridia',
    storageBucket: 'v3ridia.firebasestorage.app',
    iosBundleId: 'com.example.v3ridia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa5sXgBdWY3FUn4JNNwcIuO1lYVKbkblI',
    appId: '1:523510024166:ios:8d7cf49afc46f497ee3827',
    messagingSenderId: '523510024166',
    projectId: 'v3ridia',
    storageBucket: 'v3ridia.firebasestorage.app',
    iosBundleId: 'com.example.v3ridia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdPbPGdZweNvKS6kYFweBY_ZLrBrcGrHg',
    appId: '1:523510024166:web:1454a6c89f3d9abaee3827',
    messagingSenderId: '523510024166',
    projectId: 'v3ridia',
    authDomain: 'v3ridia.firebaseapp.com',
    storageBucket: 'v3ridia.firebasestorage.app',
    measurementId: 'G-FZ85KWZXB6',
  );
}
